---
name: "Build and deploy to github pages"

on:
  push:
    branches:
      - main  # Set a branch to deploy
    paths:
      - adblock.txt
      - hosts.txt
      - hagezi/**
      - .github/workflows/deploy-to-github-pages.yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    env:
      TARGET: ./public

    steps:
      - name: "Checkout Source"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1

      - name: "Remove gitignore"
        shell: bash
        run: rm -f "${{env.TARGET}}/.gitignore"

      - name: "Build"
        shell: bash
        run: |
          mkdir "${{env.TARGET}}/"
          cp adblock.txt "${{env.TARGET}}/adblock.txt"
          cp hosts.txt "${{env.TARGET}}/hosts.txt"
          cp -r hagezi "${{env.TARGET}}/hagezi"

      - name: "Deploy"
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "${{env.TARGET}}"
          cname: abp.markridgwell.com
